#!/bin/bash
# RemoteBackupScript(push)
#------------------------------------------------------------------
# Config:
#--------Local:
FILES_TO_BACKUP=""   # Full path, allways edning with "/"
DATABASE_TO_BACKUP=""
PATH_TO_LOG=/var/log/remote_backup_script.log
#--------Remote:
USER_REMOTESERVER=""   # user@hostname
REMOTE_PATH_FOR_BACKUPS=""   # Full path, allways edning with "/"
#--------Other varriables:
BACKUP_NAME="website_"
KEEP_BACKUP_TIME="0"   # 0 for one day, 1 for two days...
DATE_TIME=$(date +"%Y-%m-%d_%Hh")

#------------------------------------------------------------------
# Start with loging
echo "RemoteBackupScript started at $(date) with load: $(uptime | awk '{print $10 $11 $12}')" >> $PATH_TO_LOG

# Files Backup
echo "Starting to backup $FILES_TO_BACKUP" >> $PATH_TO_LOG
rsync -avW $FILES_TO_BACKUP -e 'ssh -p 22' $USER_REMOTESERVER:$REMOTE_PATH_FOR_BACKUPS$BACKUP_NAME$DATE_TIME/
echo "Backup of $FILES_TO_BACKUP finished" >> $PATH_TO_LOG

# Myslq Backup
echo "Starting to backup database: $DATABASE_TO_BACKUP" >> $PATH_TO_LOG
#mysqldump $DATABASE_TO_BACKUP | ssh -p 22 $USER_REMOTESERVER:$REMOTE_PATH_FOR_BACKUPS$BACKUP_NAMEDATE_TIME 'cat > $DATABASE_TO_BACKUP"_"DATE_TIME".sql"' 

#------------------------------------------------------------------
# Removing backups older THAN x(days)
#find $PATH_BACKUP/ -maxdepth 1 -type d -ctime +$KEEP_BACKUP_TIME -exec rm -rf {} \;
#find $PATH_BACKUP/ -maxdepth 1 -type d -exec rm -rf {} \;

# Finish with loging
echo "RemoteBackupScript finished at $(date) with load: $(uptime | awk '{print $10 $11 $12}')" >> $PATH_TO_LOG





